### ISSUE TITLE
Peek won't compile due to undefined function

### ISSUE THREAD

**Issue by alwayslivid** [HaikuArchives/Peek#17]
The program will not compile due to [this line](https://github.com/HaikuArchives/Peek/blob/b4958e6e781087b4674d73645c011b9605b26b92/source/PListItem.cpp#L19).

**Comment by Ra-V2** [comment]
I compiled it with "make" without any problems.

**Comment by korli** [comment]
But why do you think it is the right fix?

**Comment by Ra-V2** [comment]
@korli I mean before this fix.

**Comment by korli** [comment]
Wrong fix but closing anyway...
